export const MOCK_AUCTIONS = [
  {
    id: '1',
    title: 'Бабина шарена торба',
    description: 'Рачно плетена волнена торба, изработена во Галичник околу 1960 година. Единствен примерок со традиционален македонски мотив — пауново перо и гранки. Носена само на свадби во семејството.',
    seller: 'Мартина К.',
    sellerWallet: '7xKp...3mQz',
    image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&q=80',
    currentBid: 45,
    startingBid: 20,
    currency: 'USDC',
    endsAt: Date.now() + 1000 * 60 * 60 * 23,
    bids: 7,
    category: 'Текстил',
    location: 'Скопје',
    nftMinted: false,
  },
  {
    id: '2',
    title: 'Стара дедова тутунска кутија',
    description: 'Месингана кутија за тутун со врежан монограм "Г.Б." и датум 1938. Пронајдена на тавански простор во Охрид. Непосредна врска со македонскиот тутунски занает.',
    seller: 'Горан Б.',
    sellerWallet: '9mRt...7pLw',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    currentBid: 120,
    startingBid: 50,
    currency: 'USDC',
    endsAt: Date.now() + 1000 * 60 * 60 * 47,
    bids: 12,
    category: 'Антиквитети',
    location: 'Охрид',
    nftMinted: false,
  },
  {
    id: '3',
    title: 'Рачно везена покривка',
    description: 'Бела памучна покривка со цветни мотиви, рачно везена од мојата баба Стојна во 1972. Никогаш не е ставана во употреба — чувана во сандак со лаванда.',
    seller: 'Елена М.',
    sellerWallet: '3nPw...1kXv',
    image: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80',
    currentBid: 30,
    startingBid: 15,
    currency: 'USDC',
    endsAt: Date.now() + 1000 * 60 * 60 * 5,
    bids: 3,
    category: 'Текстил',
    location: 'Битола',
    nftMinted: false,
  },
  {
    id: '4',
    title: 'Дрвена резбана лула',
    description: 'Рачно резбана лула од крушово дрво. Занает кој речиси исчезна — еден од последните мајстори во Крушево ја изработил во 1985 година. Потпис на дното.',
    seller: 'Никола Р.',
    sellerWallet: '2qWs...9hJk',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    currentBid: 85,
    startingBid: 40,
    currency: 'USDC',
    endsAt: Date.now() + 1000 * 60 * 60 * 71,
    bids: 9,
    category: 'Занаети',
    location: 'Крушево',
    nftMinted: false,
  },
  {
    id: '5',
    title: 'Фотографија — Скопски базар 1955',
    description: 'Оригинална фотографија на Скопскиот базар снимена во 1955. Желатинско-сребрен процес. Видливи се дуќани кои повеќе не постојат. Единствен примерок.',
    seller: 'Сашо Д.',
    sellerWallet: '6tYu...4gBn',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    currentBid: 200,
    startingBid: 100,
    currency: 'USDC',
    endsAt: Date.now() + 1000 * 60 * 60 * 12,
    bids: 18,
    category: 'Фотографија',
    location: 'Скопје',
    nftMinted: false,
  },
  {
    id: '6',
    title: 'Македонска народна носија',
    description: 'Комплетна женска народна носија од Тетовско. Рачно изработена со автентични везови и традиционални украси. Датира од почетокот на 20 век.',
    seller: 'Весна Т.',
    sellerWallet: '8yHj...2mCp',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4012?w=800&q=80',
    currentBid: 340,
    startingBid: 200,
    currency: 'USDC',
    endsAt: Date.now() + 1000 * 60 * 60 * 36,
    bids: 22,
    category: 'Народна носија',
    location: 'Тетово',
    nftMinted: false,
  },
]

export const CATEGORIES = ['Сите', 'Текстил', 'Антиквитети', 'Занаети', 'Фотографија', 'Народна носија']
export const SORT_OPTIONS = [
  { value: 'ending',   label: 'Завршуваат наскоро' },
  { value: 'bid_high', label: 'Највисока понуда' },
  { value: 'bid_low',  label: 'Најниска понуда' },
  { value: 'bids',     label: 'Најмногу понуди' },
]
